local utils = require "core.utils"

return {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
        "MunifTanjim/nui.nvim",
        {
            "s1n7ax/nvim-window-picker",
            event = "VeryLazy",
            version = "2.*",
            opts = {
                filter_rules = {
                    include_current_win = false,
                    autoselect_one = true,
                    bo = {
                        filetype = { "neo-tree", "neo-tree-popup", "notify" },
                        buftype = { "terminal", "quickfix" },
                    },
                },
            },
            config = function(_, opts)
                require("window-picker").setup(utils.create_spec("window-picker", opts))
            end,
        },
    },
    ---@class config
    opts = {
        buffers = {
            window = {
                mappings = {
                    ["_"] = "set_root",
                    ["-"] = "navigate_up",
                    bd = "buffer_delete",
                    i = "show_file_details",
                    o = {
                        "show_help",
                        config = {
                            prefix_key = "o",
                            title = "Order by",
                        },
                        nowait = false,
                    },
                    oc = { "order_by_created", nowait = false },
                    od = { "order_by_diagnostics", nowait = false },
                    om = { "order_by_modified", nowait = false },
                    on = { "order_by_name", nowait = false },
                    os = { "order_by_size", nowait = false },
                    ot = { "order_by_type", nowait = false },
                },
            },
        },
        close_if_last_window = false,
        default_source = "filesystem",
        filesystem = {
            async_directory_scan = "auto",
            bind_to_cwd = true,
            check_gitignore_in_search = true,
            cwd_target = {
                current = "window",
                sidebar = "tab",
            },
            find_by_full_path_words = false,
            group_empty_dirs = false,
            hijack_netrw_behavior = "open_default",
            scan_mode = "shallow",
            search_limit = 50,
            use_libuv_file_watcher = false,
            window = {
                fuzzy_finder_mappings = {
                    ["<C-n>"] = "move_cursor_down",
                    ["<C-p>"] = "move_cursor_up",
                    ["<down>"] = "move_cursor_down",
                    ["<up>"] = "move_cursor_up",
                },
                mappings = {
                    ["#"] = "fuzzy_sorter",
                    ["."] = "set_root",
                    ["/"] = "fuzzy_finder",
                    ["<C-x>"] = "clear_filter",
                    ["<bs>"] = "navigate_up",
                    D = "fuzzy_finder_directory",
                    H = "toggle_hidden",
                    ["[g"] = "prev_git_modified",
                    ["]g"] = "next_git_modified",
                    f = "filter_on_submit",
                    i = "show_file_details",
                    o = {
                        "show_help",
                        config = {
                            prefix_key = "o",
                            title = "Order by",
                        },
                        nowait = false,
                    },
                    oc = { "order_by_created", nowait = false },
                    od = { "order_by_diagnostics", nowait = false },
                    og = { "order_by_git_status", nowait = false },
                    om = { "order_by_modified", nowait = false },
                    on = { "order_by_name", nowait = false },
                    os = { "order_by_size", nowait = false },
                    ot = { "order_by_type", nowait = false },
                },
            },
        },
        git_status = {
            window = {
                mappings = {
                    A = "git_add_all",
                    ga = "git_add_file",
                    gc = "git_commit",
                    gg = "git_commit_and_push",
                    gp = "git_push",
                    gr = "git_revert_file",
                    gu = "git_unstage_file",
                    i = "show_file_details",
                    o = {
                        "show_help",
                        config = {
                            prefix_key = "o",
                            title = "Order by",
                        },
                        nowait = false,
                    },
                    oc = { "order_by_created", nowait = false },
                    od = { "order_by_diagnostics", nowait = false },
                    om = { "order_by_modified", nowait = false },
                    on = { "order_by_name", nowait = false },
                    os = { "order_by_size", nowait = false },
                    ot = { "order_by_type", nowait = false },
                },
            },
        },
        git_status_async = true,
        git_status_async_options = {
            batch_delay = 10,
            batch_size = 1000,
            max_lines = 10000,
        },
        hide_root_node = false,
        log_level = "info",
        log_to_file = false,
        nesting_rules = {},
        open_files_do_not_replace_types = { "terminal", "Trouble", "qf", "edgy" },
        open_files_in_last_window = true,
        popup_border_style = "NC",
        renderers = {
            directory = {
                { "indent" },
                { "icon" },
                { "current_filter" },
                {
                    "container",
                    content = {
                        { "name", zindex = 10 },
                        {
                            "symlink_target",
                            highlight = "NeoTreeSymbolicLinkTarget",
                            zindex = 10,
                        },
                        { "clipboard", zindex = 10 },
                        {
                            "diagnostics",
                            align = "right",
                            errors_only = true,
                            hide_when_expanded = true,
                            zindex = 20,
                        },
                        {
                            "git_status",
                            align = "right",
                            hide_when_expanded = true,
                            zindex = 10,
                        },
                        { "file_size", align = "right", zindex = 10 },
                        { "type", align = "right", zindex = 10 },
                        { "last_modified", align = "right", zindex = 10 },
                        { "created", align = "right", zindex = 10 },
                    },
                },
            },
            file = {
                { "indent" },
                { "icon" },
                {
                    "container",
                    content = {
                        { "name", zindex = 10 },
                        {
                            "symlink_target",
                            highlight = "NeoTreeSymbolicLinkTarget",
                            zindex = 10,
                        },
                        { "clipboard", zindex = 10 },
                        { "bufnr", zindex = 10 },
                        { "modified", align = "right", zindex = 20 },
                        { "diagnostics", align = "right", zindex = 20 },
                        { "git_status", align = "right", zindex = 10 },
                        { "file_size", align = "right", zindex = 10 },
                        { "type", align = "right", zindex = 10 },
                        { "last_modified", align = "right", zindex = 10 },
                        { "created", align = "right", zindex = 10 },
                    },
                },
            },
            message = {
                { "indent", with_markers = false },
                { "name", highlight = "NeoTreeMessage" },
            },
            terminal = { { "indent" }, { "icon" }, { "name" }, { "bufnr" } },
        },
        resize_timer_interval = 500,
        retain_hidden_root_indent = false,
        sort_case_insensitive = false,
        source_selector = {
            content_layout = "start",
            highlight_background = "NeoTreeTabInactive",
            highlight_separator = "NeoTreeTabSeparatorInactive",
            highlight_separator_active = "NeoTreeTabSeparatorActive",
            highlight_tab = "NeoTreeTabInactive",
            highlight_tab_active = "NeoTreeTabActive",
            padding = 0,
            separator = {
                left = "▏",
                right = "▕",
            },
            show_scrolled_off_parent_node = false,
            show_separator_on_edge = false,
            sources = {
                {
                    source = "filesystem",
                },
                {
                    source = "buffers",
                },
                {
                    source = "git_status",
                },
            },
            statusline = false,
            tabs_layout = "equal",
            truncation_character = "…",
            winbar = false,
        },
        sources = { "filesystem", "buffers", "git_status" },
        use_default_mappings = true,
        use_popups_for_input = true,
        window = {
            auto_expand_width = false,
            height = 15,
            insert_as = "child",
            mapping_options = {
                noremap = true,
                nowait = true,
            },
            mappings = {
                ["<"] = "prev_source",
                ["<2-LeftMouse>"] = "open",
                ["<cr>"] = "open",
                ["<esc>"] = "cancel",
                ["<space>"] = { "toggle_node", nowait = false },
                [">"] = "next_source",
                ["?"] = "show_help",
                A = "add_directory",
                C = "close_node",
                P = {
                    "toggle_preview",
                    config = {
                        use_float = true,
                        use_image_nvim = false,
                    },
                },
                R = "refresh",
                S = "open_split",
                a = { "add", config = {
                    show_path = "none",
                } },
                c = "copy",
                d = "delete",
                e = "toggle_auto_expand_width",
                l = "focus_preview",
                m = "move",
                p = "paste_from_clipboard",
                q = "close_window",
                r = "rename",
                s = "open_vsplit",
                t = "open_tabnew",
                w = "open_with_window_picker",
                x = "cut_to_clipboard",
                y = "copy_to_clipboard",
                z = "close_all_nodes",
            },
            popup = {
                position = "50%",
                size = {
                    height = "80%",
                    width = "50%",
                },
            },
            position = "left",
            same_level = false,
            width = 40,
        },
    },
    config = function(_, opts)
        require("neo-tree").setup(utils.create_spec("neo-tree", opts))
    end,
}
